### ISSUE TITLE
truffle migrate에서 신택스 오류 

### ISSUE THREAD

**Issue by songpang** [codingeverybody/codingyahac#244]
SyntaxError: Unexpected identifier
    at REPLServer.Interface._onLine (readline.js:280:10)
    at REPLServer.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at REPLServer.onLine (repl.js:468:10)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at bound (domain.js:301:14)
    at ReplManager.interpret (C:\Users\song\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\repl.js:119:1)
    at Console.interpret (C:\Users\song\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\console.js:164:1)
    at Object.runInContext (vm.js:119:10)
    at createScript (vm.js:80:10)

간단한 토큰을 만들어 ico를 하기 위해 마이그레이션을 하려고 하는데 이런 오류가 계속뜨네요 ㅠㅠ
어디서 문제가 있는것일까요..?

**Comment by o2-basta** [comment]
뭔가 값이 할당되지 않은거 같기도 하고, 선언되지 않은 변수이기도 한거 같습니다. 

관련된 코드나 오류가 나는 부분이 어떻게 되어있는지 알수 있으면 조력자들이 자세하게 답할 수 있을거 같습니다.

**Comment by songpang** [comment]
SHSCoinCrowdSale.sol
`pragma solidity ^0.4.24;

import "./SHSCoin.sol";
import "zeppelin-solidity/contracts/crowdsale/Crowdsale.sol";

contract SHSCoinCrowdsale is Crowdsale {

    function SHSCoinCrowdsale(uint256 _rate, address _wallet)
        Crowdsale(_rate, _wallet, new SHSCoin()) {
        }

        function createTokenContract() internal returns (MintableToken) {
            return new SHSCoin();
        }
}`

SHSCoin.sol
`pragma solidity ^0.4.24;

import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";

contract SHSCoin is MintableToken {
    string public nmae = "SHS PERSONAL COIN";
    string public symbol = "JHP";
    uint8 public decimals = 18;
}`

2_deploy_contracts.js
`const SHSCoinCrowdsale = artifacts.require("./JHPCoinCrowdsale.sol")

moudule.exports = function(deployer, network, accounts) {
    //const startTime = web3.eth.getBlock(web3.eth.blockNumber).timestamp + 5
    //const endTime = startTime + (86400 * 20)
    const rate = new web3.BigNumber(1000)
    const wallet = accounts[0]

    deployer.deploy(SHSCoinCrowdsale, rate, wallet)
};`

이 세개입니다.

**Comment by songpang** [comment]
SHSCoin.sol

`pragma solidity ^0.4.24;

import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";

contract SHSCoin is MintableToken {
string public nmae = "SHS PERSONAL COIN";
string public symbol = "JHP";
uint8 public decimals = 18;
}`

**Comment by songpang** [comment]
SHSCoin.sol

``pragma solidity ^0.4.24;

import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";

contract SHSCoin is MintableToken {
string public nmae = "SHS PERSONAL COIN";
string public symbol = "JHP";
uint8 public decimals = 18;
}```

**Comment by studroid** [comment]
2_deploy_contracts.js에 보면 아래 라인이 있군요!

const SHSCoinCrowdsale = artifacts.require("./JHPCoinCrowdsale.sol")

여기서 뭔가 바꿔야 할 것 같지 않으신지..? ㅎㅎㅎ

한번 확인해보고 알려주세요!

**Comment by songpang** [comment]
SyntaxError: Unexpected identifier
    at REPLServer.Interface._onLine (readline.js:280:10)
    at REPLServer.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at REPLServer.onLine (repl.js:468:10)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at bound (domain.js:301:14)
    at ReplManager.interpret (C:\Users\song\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\repl.js:119:1)
    at Console.interpret (C:\Users\song\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\console.js:164:1)
    at Object.runInContext (vm.js:119:10)
    at createScript (vm.js:80:10)

const SHSCoinCrowdsale = artifacts.require("./SHSCoinCrowdSale.sol")
로 수정을 하여 truffle migrate를 진행하였지만 똑같은 에러가 나타납니다 ㅠㅠ

**Comment by songpang** [comment]
혹시 몰라서 새로 레파지토리를 만들어서 코드를 올려놓았습니다 ㅠㅠ
https://github.com/songpang/PRAC_SLDT 이곳입니다.
