### ISSUE TITLE
Windows 10에서 파이썬 배우는 중 에라 모르겠다가 있어서...

### ISSUE THREAD

**Issue by Metaskyer** [codingeverybody/codingyahac#261]
아나콘다 깔고, 스파이더 불러와서 실행 연습하다가 막혔어요.
import numpy as np 
요거 실행시키면, 

**************
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

runfile('C:/test/test.py', wdir='C:/test')
Traceback (most recent call last):

  File "<ipython-input-1-4911ecc89e81>", line 1, in <module>
    runfile('C:/test/test.py', wdir='C:/test')

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/test/test.py", line 8, in <module>
    import numpy as np

  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs

  File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc

  File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *

  File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx

  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

************************

뜨네요. 

어케해야 할까요?

**Comment by o2-basta** [comment]
pip install numpy
이렇게 설치하시면 됩니다.

**Comment by Metaskyer** [comment]
해 볼께요.^^

**Comment by Metaskyer** [comment]
(base) C:\Users\hayah>pip install numpy
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (1.14.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
***********
요게 나와요.

**Comment by Metaskyer** [comment]
pip3 uninstall numpy -> pip install numpy하니 프롬프트에서는 되는데, 비트나미로 설치한 아파치 상에서는  역시 같은 에러가 나오네요. 

아나콘다 깔고, 비트나미 깔고 파이썬으로 엑셀 파일 가지고 원하는 통계를 구현해 보고 싶은게 있는데요. 

윈도우10 기반에서 어떤 설정이 더 필요할까요? 

아니면 다른 환경이 필요하다면 조언 구합니다. 

감사합니다.
