### ISSUE TITLE
[안드로이드] 프래그먼트에서 startActivity 문제..

### ISSUE THREAD

**Issue by Diocto** [codingeverybody/codingyahac#287]
안녕하세요. 간단한 단어장 앱을 만들고 있는 diocto 라고 합니다.

지금 현재 한 액티비티 내에 소속된 3개의 프래그먼트들이 존재하고, 그 중 한 프래그먼트 내의 버튼을 클릭해서 다른 액티비티를 시작하려고 하는데 오류가 생겨 질문드립니다.

현재 아래와 같이 프래그먼트에서 액티비티 시작 시 getActivity를 통해 액티비티 이동을 해야 된다는 정보를 검색해 수행해 봤지만, 다음과 같은 로그캣이 떴습니다. 
```
       public void clickedShowWordGroupList(View view) {
        Intent intent = new Intent(getActivity(), WordListViewActivity.class);
        startActivity(intent);
    }
```
```
//호출되는 액티비티
public class WordListViewActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_word_list);

        ListView listView;
        WordListViewAdapter adapter;
        adapter = new WordListViewAdapter();

        listView = findViewById(R.id.wordListView);
        listView.setAdapter(adapter);

        //adapter.addItem("testName","testNum","testNotNum");
    }
}
```
```
//Logcat
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.andoidtown.ai_vocabulary, PID: 26800
                  java.lang.IllegalStateException: Could not find method clickedShowWordGroupList(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'lookWordsListButton'
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:424)
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:381)
                      at android.view.View.performClick(View.java:6877)
                      at android.widget.TextView.performClick(TextView.java:12651)
                      at android.view.View$PerformClick.run(View.java:26069)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6938)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
![image](https://user-images.githubusercontent.com/17712693/43587338-f51051ec-96a4-11e8-851b-f02410336a7c.png)

위 3개 버튼은 프래그먼트를 이동하는 뷰페이저 내의 버튼(탭)들이고, 현재 보이는 프래그먼트에서 '단어목록' 보기를 눌러 이동하려고 하면 위와 같은 로그캣이 뜨면서 앱이 종료됩니다. 무엇이 문제인가요?

**Comment by InyoungAum** [comment]
로그를 분석해보면 버튼을 눌렀을때 `onClick`에 할당한 메소드인 `clickedShowWordGroupList`를 찾지 못해서 생기는 문제입니다. 
`Fragment`에서 작성한 함수를 `onClick`으로 할당할 때 찾지 못하는 경우가 있어 해당 함수를 `Fragment`를 가지고 있는 `Activity`나 `setOnClickListener`로 할당하시면 해결될 것 같습니다.

**Comment by InyoungAum** [comment]
`Activity`에서는 `setContentView`를 통해 xml파일을 할당해주면 바로 `findViewById`로 사용이 가능하지만 
`Fragment`에서는 View를 `inflate`해서 해당 변수가 view를 들고있고 그걸 최종적으로 리턴해주어서 그렇습니다. 
아마 해당 `Fragment`에서는 `rootView`에 `inflate`를 하고 계신것으로 생각됩니다!

**Comment by Diocto** [comment]
@InyoungAum 
아 그렇네요! 도저히 해결이 안되서 Do it 안드로이드 예제대로 했었는데 ```ViewGroup rootView``` 변수에 ```inflate```를 한 다음 ```rootView``` 에서 ```findViewById``` 메서드를 호출하네요! (```rootView.findViewById```) 이제 왜 안되던건지 이해가 갔습니다. 감사합니다!

추가로 질문을 드리자면, 위의 ```inflate```한 변수를 return을 한 다음에는 ```inflate``` 했던 ViewGroup를 다시 참조해서 id를 찾을 수는 없는건가요? 이 문제를 해결하기 전에 프래그먼트 생명주기를 관리하는 함수를 ```Override``` 해서 바로 ```findViewById```를 호출했는데 해당 View를 찾지 못해서 ```NullPointException```에러가 났었습니다.

아래 코드는 찾고자 했던 View가 있던 Fragment에서 Override한 함수입니다. 아래와 같이 코드를 작성했더니 잘 돌아갔었습니다.  위의 추가질문을 다시 정리하자면, 저기서 바로 return을 한다음에는 원하는 View를 다시 찾을 수 없는지 궁금합니다.
```
 @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        ViewGroup rootView = (ViewGroup) inflater.inflate(R.layout.fragment_management_words, container, false);
        showWordGroupListButton = rootView.findViewById(R.id.showWordsListButton);
        showWordGroupListButton.setOnClickListener( new View.OnClickListener(){
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(getActivity(), WordListViewActivity.class);
                startActivity(intent);
            }
        });

        return rootView;
    }
```

**Comment by InyoungAum** [comment]
@Diocto 
Fragment가 가지고있는 메소드중 `getView()` 를 사용하면 해당 Fragment의 최상단 VIew를 가져올 수 있습니다. 다만 `onCreateView`가 호출되기 이전에 사용하신다면 null로 넘어올 수 있습니다. 
다른 방법으로는 onCreateView에서 rootView를 맴버 해당 Fragment에 생성된 멤버변수로 넘기는 방법도 있습니다. 

해당 내용은 질문의 제목과 맥락이 벗어나서 다시 답변을 달아주시면 다른분들이 참고하실때 좋을 것 같습니다!
