### ISSUE TITLE
android firebase 읽기 오류

### ISSUE THREAD

**Issue by haeyonghahn** [codingeverybody/codingyahac#388]
본 양식은 질문의 막연함을 도와주기 위한 도움을 드리기 위한 것입니다. 양식을 참고해서 자유롭게 적어주세요. 

# 해결하고자 하는 문제
firebase 문제 
FirebaseAdapter.startListening() 와 FirebaseAdapter.stopListening() 문제인거같습니다 

# 코드 혹은 오류
```
코드 : 

public class MainActivity extends AppCompatActivity implements GoogleApiClient.OnConnectionFailedListener {

    private FirebaseRecyclerAdapter<ChatMessage, MessageViewHolder> mFirebaseAdapter;

    public static final String MESSAGES_CHILD = "messages";
    // 데이터베이스에 쓰기 위한 객체
    private DatabaseReference mFirebaseDatabaseReference;
    private EditText mMessageEditText;

    // 인증 객체
    private FirebaseAuth mAuth;
    private RecyclerView mMessageRecyclerView;

    private FirebaseUser mFirebaseUser;

    // 사용자 이름과 프로필 사진을 저장할 변수
    private String mUsername;
    private String mPhotoUrl;

    // Google계정과 무언가 할려면 google api가 필요하다.
    private GoogleApiClient mGoogleApiClient;

    @Override
    public void onConnectionFailed(@NonNull ConnectionResult connectionResult) {

    }

    public static class MessageViewHolder extends RecyclerView.ViewHolder {

        TextView nameTextView;
        TextView messageTextView;
        CircleImageView photoImageView;
        ImageView messageImageView;

        public MessageViewHolder(View itemView) {
            super(itemView);

            nameTextView = itemView.findViewById(R.id.nameTextView);
            messageTextView = itemView.findViewById(R.id.messageTextView);
            photoImageView = itemView.findViewById(R.id.photoImageView);
            messageImageView = itemView.findViewById(R.id.messageImageView);
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mFirebaseDatabaseReference = FirebaseDatabase.getInstance().getReference();
        mMessageEditText = findViewById(R.id.message_edit);
        mMessageRecyclerView = findViewById(R.id.message_recycler_view);

        findViewById(R.id.send_button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ChatMessage chatmessage = new ChatMessage(mMessageEditText.getText().toString(), mUsername, mPhotoUrl, null);
                mFirebaseDatabaseReference.child(MESSAGES_CHILD)
                        // push하면 새로운 데이터를 넣는 것이다. 그러면서 자동으로 id가 생긴다.
                        .push()
                        .setValue(chatmessage);
                mMessageEditText.setText("");
            }
        });

        // GoogleApiClient 초기화
        mGoogleApiClient = new GoogleApiClient.Builder(this)
                // 자동으로 manage할 수 있다는 것
                .enableAutoManage(this, this)
                // api 지정. 옵션을 줄 수 있다. 옵션을 안주면 기본값으로 됨.
                .addApi(Auth.GOOGLE_SIGN_IN_API)
                .build();

        mAuth = FirebaseAuth.getInstance();
        mFirebaseUser = mAuth.getCurrentUser();
        // 로그인을 안한 상태라면. 유저가 null이라면
        if (mFirebaseUser == null) {
            startActivity(new Intent(this, SignInActivity.class));
            finish();
            return;
        }
        // 로그인이 됬다면
        else {
            mUsername = mFirebaseUser.getDisplayName();
            if (mFirebaseUser.getPhotoUrl() != null) {
                mPhotoUrl = mFirebaseUser.getPhotoUrl().toString();
            }
        }

        // 이 query는 messages에 대한 전체 내용을 얻겠다는 의미.
        Query query = mFirebaseDatabaseReference.child(MESSAGES_CHILD);
        FirebaseRecyclerOptions<ChatMessage> options = new FirebaseRecyclerOptions.Builder<ChatMessage>()
                // 쿼리에 결과를 어떤 형태로 받을 것인지. ChatMessage.class 형태로 받을 것이다.
                .setQuery(query, ChatMessage.class)
                .build();

        // FirebaseRecyclerAdapter 생성자에서 Options를 요구한다. 일단 쿼리부터 만들어야한다. 내가 어떤 쿼리를 수행할 것이냐.
        mFirebaseAdapter = new FirebaseRecyclerAdapter<ChatMessage, MessageViewHolder>(options) {
            @Override
            protected void onBindViewHolder(MessageViewHolder holder, int position, ChatMessage model) {
                holder.messageTextView.setText(model.getText());
                holder.nameTextView.setText(model.getName());
                if (model.getPhotoUrl() == null) {
                    // vector image를 넣을 떄는 ComtextCompat.
                    holder.photoImageView.setImageDrawable(ContextCompat.getDrawable(MainActivity.this,
                            R.drawable.ic_account_circle_black_24dp));
                } else {
                    // glide를 사용해서 image를 뿌리기.
                    Glide.with(MainActivity.this)
                            .load(model.getPhotoUrl())
                            .into(holder.photoImageView);
                }
            }

            @Override
            public MessageViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_message, parent, false);
                return new MessageViewHolder(view);
            }

            @Override
            public void onError(DatabaseError error) {
                super.onError(error);
            }
        };

        mMessageRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mMessageRecyclerView.setAdapter(mFirebaseAdapter);
    }

    // firebaseAdapter는 activity 생명주기에 따라서 상태를 모니터링하게하고 멈추게하도록 되어있다.
    // 이걸 꼭 추가해줘야 데이터를 읽어올 수 있다. onStart, onStop
    @Override
    protected void onStart() {
        super.onStart();
        mFirebaseAdapter.startListening();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mFirebaseAdapter.stopListening();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main, menu);
        // 이벤티가 잘 처리됬다면 true;
        return true;
    } 
```
```
오류 : Logcat
08-07 15:46:49.081 23966-23966/com.example.part32_firebasechatexam E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.part32_firebasechatexam, PID: 23966
    com.google.firebase.database.DatabaseException: Class com.example.part32_firebasechatexam.ChatMessage does not define a no-argument constructor. If you are using ProGuard, make sure these constructors are not stripped.
        at com.google.android.gms.internal.zzelx.zze(Unknown Source:44)
        at com.google.android.gms.internal.zzelw.zzb(Unknown Source:196)
        at com.google.android.gms.internal.zzelw.zza(Unknown Source:0)
        at com.google.firebase.database.DataSnapshot.getValue(Unknown Source:10)
        at com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:23)
        at com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:14)
        at com.firebase.ui.common.BaseCachingSnapshotParser.parseSnapshot(BaseCachingSnapshotParser.java:32)
        at com.firebase.ui.common.BaseObservableSnapshotArray.get(BaseObservableSnapshotArray.java:45)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.getItem(FirebaseRecyclerAdapter.java:103)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.onBindViewHolder(FirebaseRecyclerAdapter.java:118)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20672)
08-07 15:46:49.086 23966-23966/com.example.part32_firebasechatexam E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2793)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2320)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-07 15:46:49.125 1567-1567/? E/lowmemorykiller: Error writing /proc/23966/oom_score_adj; errno=22
08-07 15:46:49.179 1825-1898/? E/InputDispatcher: channel '7cc971f com.example.part32_firebasechatexam/com.example.part32_firebasechatexam.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-07 15:46:52.295 1825-1945/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
08-07 15:46:54.969 1825-1839/? E/memtrack: Couldn't load memtrack module

```

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
- build.gradle
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 26

    defaultConfig {
        applicationId "com.example.part32_firebasechatexam"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.google.firebase:firebase-auth:11.8.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'de.hdodenhof:circleimageview:2.1.0'
    implementation 'com.google.android.gms:play-services-auth:11.8.0'
    implementation 'com.google.firebase:firebase-core:11.8.0'
    // firebase 데이터베이스를 사용하면서 거기에 관련된 ui에 도움이되는 adapter라던지 이런것들을 제공하는 라이브러리이다.
    implementation 'com.firebaseui:firebase-ui-database:3.1.0'
    implementation 'com.github.bumptech.glide:glide:4.3.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.0'
} 

# 시도해본 방법
소스 하나하나 주석을 달면서 오류가 발생한 부분이 어디인지 확인한 결과,
onStart() 와 onStop()에 작성되어있는 mFirebaseAdapter.startListening()와 mFirebaseAdapter.stopListening() 부분에서 주석을 취소하고 실행시키면 오류가 발생되는 것을 확인하였습니다. 그리고나서, 구글링을 하였습니다. 하지만 adapter를 초기화시키는 부분은 onCreate()에서 작성되어있고 firebase Database에 저장된 데이터도 알맞게 갖춰져있고 데이터 클래스에 생성자도 알맞게 있습니다. 또한, 버전 문제인지 확인하기위해서 build.gradle에 있는 버전 및 라이브러리에 실수가 있나 확인도 해보았는데 올바르게 되어있습니다. 하지만 도저히 어떤 오류인지 도저히 알 수가 없습니다.

**Comment by InyoungAum** [comment]
https://stackoverflow.com/questions/47706601/users-does-not-define-no-argument-constructor
이 링크가 도움이 될 수 있을 것 같은데 
`ChatMessage`라는 객체의 생성자중 하나를 `argument`가 없이 하나 만들어보시겠어요?

**Comment by yong7317** [comment]
답변 감사드립니다 :) 한 번 시도해보도록 하겠습니다 👍
