### ISSUE TITLE
사이썬(pyx) 파일 import 문제

### ISSUE THREAD

**Issue by sunwmoon** [codingeverybody/codingyahac#398]
# 해결하고자 하는 문제
사이썬(pyx) 파일 import 시에 에러가 발생합니다.

스웨덴 친구가 python으로 만든 pylist 프로그램 (데이터 분석 프로그램 입니다)인데,
유독 제 노트북에서만 실행이 되질 않습니다.
제 노트북은 i5, ASUS, Win10이고, 독일에서 구매,
ASCII 코드 문제인 것 같아 기본 언어를 한글에서 영어로 바꾸었는데도 안되네요.

lstread.pyx 파일이 import 안되는 문제가 있는 것 같습니다.
제가 파이썬은 이제 입문한지 3주차라서... 가르침이 필요합니다.

# 코드 혹은 오류
Traceback (most recent call last):
  File "C:\KTH\Pylist\pylist_v19_full\lstGUI.py", line 3, in <module>
    import tkinter as tki, tkinter.font as tkf, guiFunctions as gf, dataFunctions as df, \
  File "C:\KTH\Pylist\pylist_v19_full\guiFunctions.py", line 4, in <module>
    import lstread as lr, tkinter as tki
**ModuleNotFoundError: No module named 'lstread'**

# 환경
사용중인 운영체제 Windows 10
언어 Python 3.7

# 시도해본 방법
동일한 프로그램을 컴파일을 통해 EXE로 만들어 실행한 경우에는 아래와 같은 에러가 나서 언어 문제인줄 알았는데, 아닌 것 같아 문의 드립니다.

ValueError: _getfullpathname: embedded null character
lstGUI returned -1

**Comment by blackdew** [comment]
pip를 설치하신 후에 (http://codingdojang.com/scode/371)
lstread 모듈을 설치해보세요. :) 
```
pip install lstread
```

**Comment by sunwmoon** [comment]
답변 감사합니다. 이것저것 하면서 해봤었는데, 아래와 같이 나오네요...
Collecting lstread
  Could not find a version that satisfies the requirement lstread (from versions: )
No matching distribution found for lstread

**Comment by blackdew** [comment]
아하.. 제가 글을 제대로 이해 못하고 답을 드렸네요 ㅠㅠ
lstread.pyx 는 스웨덴 친구분이 직접 작성한 프로그램이었군요. 
python path가 어디를 바라보고 있는지 확인을 해보시면 좋을 것 같아요. 
```
import os
os.getcwd()
```

그리고 아래의 글을 참고해주시면 될 것 같습니다.
https://stackoverflow.com/questions/24722212/python-cant-find-module-in-the-same-folder

**Comment by sunwmoon** [comment]
답변 정말 감사합니다. 
os.getcwd() 결과는 아래와 같고, 해당 폴더에 lstread.pyx 파일이 있습니다.
'C:\\KTH\\Pylist\\pylist_v19_full'

보내주신 링크 참고해서 lstread.pyx 파일 상단에 아래와 같이 작성해 첨부했습니다.
```
import sys, os
sys.path.append('/path/to/pylist_v19_full')
```

그래도 동일한 에러가 나오네요...

**Comment by blackdew** [comment]
아래와 같이 해보시겠어요? 

```
sys.path.append('C:\KTH\Pylist\pylist_v19_full')
```

**Comment by sunwmoon** [comment]
계속 감사합니다. 계속 같은 에러가 나네요...
/, //, \, \\ 모두 사용해 봤는데 동일했습니다. 저도 매일 조금씩 이거 해결하려고 찾아보고 있는데 path 문제, font_manager 문제 까지 확인해 봤는데 안되네요;;

**Comment by blackdew** [comment]
환경을 잘 잡지 못하면 종종 한참 삽질하게 되지요 :) 
여러가지 환경적인 이유로 어려움을 겪는 것은 매우 좋은 경험입니다. 
뼈가 되고 살이 될거에요. 너무 고통받지 않으셨으면 좋겠습니다. 
저도 결국 해결을 해드릴 수 있는지는 잘 모르겠네요. ㅎㅎㅎ

1. python2 버전에서 동작하는 코드인지 한번 확인해 보세요. 

2. 아래의 코드로 import를 시도해 보시기 바랍니다. 
```
from . import lstread as lr
```

3. __init__.py 파일을 추가해 보시기 바랍니다. 
다음 문서를 참고해주세요. 
https://wikidocs.net/1418 

4. pyx는 import가 아니라 cimport를 사용해야 한다는 글도 있네요. 한 번 시도해 보면 좋겠습니다. 

5. 다음의 링크글을 찾았는데요. 두 개의 파일이 circular import를 하는 경우에도 module import가 실패한다고 되어있네요. lstread 내에서 import 되어있는 목록을 찾으시고, 그곳에서 lstread를 import 하고 있는지 확인해 보세요. 
https://groups.google.com/forum/#!topic/cython-users/6trL0V1bLx4

--------

그래도 안되면.. 
동작이 되는 컴퓨터를 알고 계시다면 그 곳의 환경과 
안되는 곳의 환경을 비교하면서 찾아 보시는 것을 추천드립니다. 

해결이 되면 좋겠네요!
