### ISSUE TITLE
html_snitizer 설치했는데 no module 이라는 에러가 뜹니다.

### ISSUE THREAD

**Issue by limik1004** [codingeverybody/codingyahac#456]
# 해결하고자 하는 문제

# 코드 혹은 오류
```
[Tue Aug 14 09:57:15.273286 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215: Traceback (most recent call last):\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
[Tue Aug 14 09:57:15.273286 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215:   File "C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py", line 4, in <module>\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
[Tue Aug 14 09:57:15.273286 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215:     import cgi, os, view, html_sanitizer\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
[Tue Aug 14 09:57:15.273286 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215:   File "C:\\Bitnami\\wampstack-7.1.19-0\\apache2\\htdocs\\view.py", line 1, in <module>\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
[Tue Aug 14 09:57:15.274287 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215:     import os, html_sanitizer\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
[Tue Aug 14 09:57:15.274287 2018] [cgi:error] [pid 5276:tid 1260] [client 127.0.0.1:64668] AH01215: ModuleNotFoundError: No module named 'html_sanitizer'\r: C:/Bitnami/wampstack-7.1.19-0/apache2/htdocs/index.py
```

# 환경
windows10

# 시도해본 방법
제 파일은 벡업해두고 이고잉님이 올리신 파일중 #!python으로만 수정해 대신 넣어 테스트해봤습니다.  결과는 같습니다.

**Comment by ghdalsrldi** [comment]
Python인가요? PHP 인가요?
Python이라면 virtualenv 등의 가상환경을 사용하고 계신가요?
환경과 작성한 코드를 공유해 주시면 정확한 답변을 하는데 도움이 될 것 같습니다.
