### ISSUE TITLE
express-ejs-layout 적용 시 is not defined 오류

### ISSUE THREAD

**Issue by beyondalpha10** [codingeverybody/codingyahac#591]
# 해결하고자 하는 문제
express-ejs-layout 적용하는데 랜더에서 설정해준 mysql의 쿼리의 결과가 계속 is not defined 오류가 뜹니다. 데이터는 잘 나오는데 터미널에 계속 일부 파일의 404 오류와 함께 저 오류가 뜨네요 

# 코드 혹은 오류
```
routes/index.js

var express = require('express');
var router = express.Router();
var mysql_dbc = require('../db_config')();
var connection = mysql_dbc.init();
mysql_dbc.test_open(connection);

/* GET home page.*/
router.get('/', function(req, res, next) {
  var sql = 'SELECT * FROM user';
  connection.query(sql, function(err,result){
    res.render('layout', {user:result});
  });
});

module.exports = router;


layout.ejs

<!DOCTYPE html>
<html lang="ko">
<head>
    <% include ./head.ejs %>
</head>
<body>
    <header>
        <% include ./navbar.ejs %>
        <!--navbar side-->
        <div class="container-fluid">
          <div class="row">
           <% include ./sidebar.ejs %>
    </header>
            <!--content-->
            <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
            <h3 class="page-header">
                <% include ./home.ejs %></h3>
        </main>
          </div>
        </div>
    <footer>
        푸터영역
    </footer>
    <% include ./script.ejs %> 
</body>
</html>

home.ejs

        <%= user[0].nic) %>님의 GSP
            <!--Goal-->
            <% include ./data/goal/no-goal.ejs %>
            <% include ./data/goal/gysnpn.ejs %>

오류

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www start`
mysql is connected successfully.
GET / 200 86.090 ms - 11304
GET /bootstrap/css/bootstrap.min.css 304 8.812 ms - -
GET /bootstrap/css/templates.css 304 16.705 ms - -
GET /bootstrap/css/home.css 304 16.099 ms - -
GET /bootstrap/docs/assets/js/ie-emulation-modes-warning.js 304 5.276 ms - -
GET /images/goal.png 304 3.077 ms - -
GET /bootstrap/js/bootstrap.min.js 304 6.311 ms - -
GET /bootstrap/docs/assets/js/docs.min.js 304 2.343 ms - -
GET /bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js 304 6.762 ms - -
GET /assets/js/vendor/popper.min.js 404 70.339 ms - 2434
GET /dist/js/bootstrap.min.js 404 71.196 ms - 2434
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20
GET /assets/js/ie10-viewport-bug-workaround.js 404 119.800 ms - 2434
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20
GET /assets/js/vendor/popper.min.js 404 21.023 ms - 2434
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20
GET /dist/js/bootstrap.min.js 404 18.424 ms - 2434
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20
GET /assets/js/ie10-viewport-bug-workaround.js 404 21.642 ms - 2434
ReferenceError: C:\Users\심현보\Desktop\gsp4\views\layout.ejs:17
    15|             <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main"></main>
    16|             <h3 class="page-header">
 >> 17|                 <% include ./home.ejs %></h3>
    18|         </main>
    19|           </div>
    20|         </div>

C:\Users\심현보\Desktop\gsp4\views\home.ejs:1
 >> 1|         dddddddddddddddddddd<%= user[0].nic %>님의 GSPddddddddd
    2|             <!--Goal-->
    3|             <% include ./data/goal/no-goal.ejs %>
    4|             <% include ./data/goal/gysnpn.ejs %>

user is not defined
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:56:26)
    at eval (eval at compile (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:592:12), <anonymous>:101:10)
    at returnedFn (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:623:17)
    at tryHandleCache (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:251:36)
    at View.exports.renderFile [as engine] (C:\Users\심현보\Desktop\gsp4\node_modules\ejs\lib\ejs.js:480:10)
    at View.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\심현보\Desktop\gsp4\node_modules\express\lib\response.js:1008:7)
    at C:\Users\심현보\Desktop\gsp4\node_modules\express-ejs-layouts\lib\express-layouts.js:113:20

  

```

# 환경
window10, node.js, express, ejs, ejs-layout, mysql

# 시도해본 방법

**Comment by yoobato** [comment]
`<% include ./home.ejs %>` 이 부분을,
`<% include('home', {user: user}); %>` 으로 바꿔보시겠어요?

**Comment by beyondalpha10** [comment]
> `<% include ./home.ejs %>` 이 부분을,
> `<% include('home', {user: user}); %>` 으로 바꿔보시겠어요?

그렇게 바꾸면 화면도 아예 안나오고, 에러는 같은 에러 계속 나요.
ejs-layout을 적용 안하면 저 에러가 안나거든요.
app.js가 문제일까요?

app.js

var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var scheduleRouter = require('./routes/schedule');

var app = express();
var expressLayouts = require('express-ejs-layouts');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(expressLayouts);
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static((__dirname, 'public')));


app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/schedule', scheduleRouter);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

**Comment by yoobato** [comment]
답변이 늦어 죄송합니다.

혹시, `layout.ejs`를 레이아웃으로 사용하시려던게 아니셨나요?
만약 레이아웃으로 사용하시려는게 아니라면, 굳이 `express-ejs-layouts` 모듈을 사용하실 필요가 없습니다.

express-ejs-layouts 모듈은, 기본 레이아웃을 하나 만들고, 그 안에 `<%- body %>` 라는 컨테이너를 만들어,
다른 뷰(ejs) 파일들의 컨텐츠가, `<%- body %>` 안에 대체되도록 하는 구조입니다. 데이터를 넘길 때는, `<%- contentFor('변수명') %>` 이렇게 사용하구요.

[express-ejs-layouts](https://www.npmjs.com/package/express-ejs-layouts) 모듈의 README를 다시 한 번 확인해보시고, 지금 하시려는 프로젝트에 맞는 모듈인지를 먼저 확인해보시는 것이 좋을 것 같습니다.
