### ISSUE TITLE
(androidStudio,Kotlin) RoomDB에서 Fragment의 EditText로 String 넘기기 질문입니다

### ISSUE THREAD

**Issue by 3always8** [codingeverybody/codingyahac#697]
# 해결하고자 하는 문제
현재 RoomDB를 사용하고 있습니다.
RoomDB에 저장된 String을
Fragment에 있는 editText에 넣으려고 하는데 NullPointerException 오류가 나고 있습니다.
해당 Fragment : PeopleFragment

# 오류
2019-08-03 20:09:04.846 18400-18400/com.ssong.willy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ssong.willy, PID: 18400
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:51)
        at android.text.Editable$Factory.newEditable(Editable.java:145)
        at com.ssong.willy.PeopleFragment.onCreateView(PeopleFragment.kt:32)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2718)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
2019-08-03 20:09:04.848 18400-18400/com.ssong.willy E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

# 코드

[https://github.com/3always8/Willy/tree/master/app/src/main/java/com/ssong/willy](https://github.com/3always8/Willy/tree/master/app/src/main/java/com/ssong/willy) 
MainActivity 하나에
PeopleFragment
MoneyFragment
FuneralFragment
이렇게 3개가 연결되어있습니다.

PeopleFragment의 onCreateView에서 문제가 생겼습니다.

# 환경
운영체제 : Mac Mojave 10.14.5(18F132)
언어 : Kotlin
Android Studio 3.4

# 시도해본 방법
1.MainActivity에서는 DB 생성만 하고
PeopleFragment에서 DB에저장된 String을 불러오기+editText 에 넣는 방법
2.MainActivity에서 DB 생성+DB에저장된 String을 Array<string>에 저장
PeopleFragment에서 editTextView에 넣기만 하는 방법

2번이 현재 코드입니다.
둘 다     java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
오류가 났습니다.

**Comment by progh2** [comment]
출력될 예제 데이터는 들어가 있는건가요? 
데이터가 없어서 가져올 것이 없으니까 그런 결과가 될 수도 있을 것 같아서요~

**Comment by 3always8** [comment]
> 출력될 예제 데이터는 들어가 있는건가요?
> 데이터가 없어서 가져올 것이 없으니까 그런 결과가 될 수도 있을 것 같아서요~

원래 계획은 앱을 구동시켜서 데이터를 저장한 뒤
다시 앱을 켜서 확인해보는 것이었는데
맨처음에 데이터가 없어서 계속 오류가 났던 것 같습니다.
감사합니다!
