### ISSUE TITLE
python 크롤링 예제 풀고 있는데 오류가 발생합니다.

### ISSUE THREAD

**Issue by gyobeom-koo** [codingeverybody/codingyahac#967]
#해결하고자 하는 문제

https://heodolf.tistory.com/81?category=897877 사이트를 보고 크롤링을 연습하고 있습니다.

앞에서 나온 설명까지는 모두 수행이 되었는데...마지막 파싱 함수까지 넣고 crawl.py를 수행하면 오류가 발생합니다..

# 코드 혹은 오류
/Users/gugyobeom/PycharmProjects/shop_crawler/venv/bin/python /Users/gugyobeom/PycharmProjects/shop_crawler/venv/crawl.py
Traceback (most recent call last):
  File "/Users/gugyobeom/PycharmProjects/shop_crawler/venv/crawl.py", line 3, in <module>
    from crawler import SeleniumRequest
  File "/Users/gugyobeom/PycharmProjects/shop_crawler/venv/crawler/__init__.py", line 14, in <module>
    self._make_chrome_options(options)
NameError: name 'self' is not defined

# 환경
MAC OS를 사용하고 있으며 Python으로 수행하였습니다.

# 시도해본 방법
crawl.py, __init__.py, parser.py의 디렉토리를 옮겨봄.

**Comment by byskull** [comment]
self.options = [ '--headless', '--log-level=3', '--disable-logging', '--no-sandbox', '--disable-gpu' ]
 self._make_chrome_options( options ) 
이 줄을 같은 들여쓰기로 해서 def __init__(self, driver_path, options=None): 밑에 있는 구문으로 처리하게 되야 하는듯한데
예제에서 탭처리가 잘못됐는지 그렇게 안 보이네요. 탭 두개 넣어보세요. 위에 self.options 와 같게요.
